### ISSUE TITLE
Please don't bundle libraries 

### ISSUE THREAD

**Issue by jvoisin** [magne4000/festival#19]
It's not cool to bundle libraries (like mutagen); what about trusting the package manager of the user instead? Or do you need a special version of mutagen?

**Comment by magne4000** [comment]
I included mutagen to avoid installing/using pip (mutagen version is too old in most package managers)

**Comment by jvoisin** [comment]
`pip` should die in a pit of fire.
On the other hand, [Debian Jessie]( https://packages.debian.org/jessie/python-mutagen ) is shipping 1.25, so, please consider removing this dep' in a couple of weeks ;)

**Comment by magne4000** [comment]
Waiting at least for next Ubuntu LTS because 14.04 doesn't even ships python3-mutagen

**Comment by jvoisin** [comment]
Fair enough.
