### ISSUE TITLE
Cool features

### ISSUE THREAD

**Issue by Hyask** [magne4000/festival#38]
It would be super nice to have the choice in the config file between the tags or the folder as default view.

Moreover, clicking on the play button of a track always adds the whole album to the playlist. It would be cool to have the possibility to add just one track, clearing the playlist at the same time, or simply playing it at the tail of the list without emptyiyiyng it.

* [x] config file to choose default tags source
* ~~a way to choose between adding 1 song or whole album when track is added to the playlist~~

**Comment by magne4000** [comment]
c9adb00

**Comment by magne4000** [comment]
I'll add an option to clear the playlist separatly
