### ISSUE TITLE
Cropping

### ISSUE THREAD

**Issue by jvoisin** [magne4000/festival#5]
It would be cool to indicate when song titles are cropped, or to extend the container to show it entirely.

![non-crop]( http://uppix.com/f-crop552cd1990018bd1f.jpg ) 

On the screenshot, the original title is *Risk is My Business...and Business is Risky*

**Comment by magne4000** [comment]
The cropped titles are in fact ID3v1 tags, so it's just the characters limit imposed by it.
So either the tracks do not have ID3v2, or the taglib library does not succeed to read them, nothing that I can really fix on festival side.

**Comment by jvoisin** [comment]
Since the screenshot is from your server, you can fix it by re-tagging your library in IV3v2 :smiley_cat:

**Comment by magne4000** [comment]
For those particular tracks (and many other) it reads the ID3v2 but it is truncated too, because it was copied from ID3v1 (few years ago). I know that I have those tracks to clean but it take time to do it ... so perhaps later :smiley_cat:
