### ISSUE TITLE
Console corrompue

### ISSUE THREAD

**Issue by gnikwo** [magne4000/festival#50]
En lançant la commande : ./festival.py start
et en essayant d’accéder à l'interface web en passant pas nginx qui fait une redirection via proxy_pass,
la console devient complétement corrompue et inutilisable. Forcé de fermer cette session pour reprendre un fonctionnement normal.
![prompt corrupted](https://cloud.githubusercontent.com/assets/9805355/21931137/0a5327ec-d99a-11e6-810a-d5039aa916d4.png)

**Comment by magne4000** [comment]
Mauvaise configuration proxy, une requête HTTPS arrivait directement sur festival
