### ISSUE TITLE
Glow on the "+" sign

### ISSUE THREAD

**Issue by jvoisin** [magne4000/festival#8]
There is a *+* sign next every artist, it would be cool to make it glow when the mouse is over it, like the *play* and *add* button.

Also, what about using an other sign instead of a *+*, since it's already used to **add** to the playlist?

**Comment by magne4000** [comment]
The artist name itself also triggers expand/collapse when clicked.
When the artist name or the "+" sign are hovered it already changes slightly the text-shadow of both elements.
I think that changing the "+" sign to another sign like :arrow_forward: :arrow_down_small: would already be a good thing to do.

**Comment by jvoisin** [comment]
It would be great to make the change a bit more visible then :water_buffalo:
